name: CI/CD Pipeline

on:
  push:
    branches: [dev, main]  # Triggers on push to dev/main
  pull_request:
    branches: [dev]        # Triggers on PRs to dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4  # Replace with Python/Java/etc. as needed
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run lint  # ESLint, Pylint, etc.

  build:
    needs: [test, lint]  # Depends on test/lint passing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run build  # Builds the app (e.g., React, Next.js)
      # Optional: build Docker image
      - run: docker build -t myapp:${{ github.sha }} .
